### ISSUE TITLE
Date- und Time-Picker sind nicht per Tastatur bedienbar

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/mcalendar#10]
Leider kann man in die Inputfelder nichts eintippen, sondern ist gezwungen, die Picker zu verwenden.

**Comment by joachimdoerr** [comment]
Stimmt, werde das ändern. Ggf. wäre diese Datepicker noch etwas: https://github.com/uxsolutions/bootstrap-datepicker

**Comment by joachimdoerr** [comment]
Gefixt: https://github.com/FriendsOfREDAXO/mcalendar/commit/1e8be904dee2335e0fa02b5dad391cea92bf95bf
