### ISSUE TITLE
Rechte:: Mcalender wird angezeigt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mcalendar#13]
MCalender wird angezeigt obwohl kein Recht in den Rollen vergeben wurde. 
![bildschirmfoto 2016-11-05 um 11 11 48](https://cloud.githubusercontent.com/assets/791247/20029294/e195b5ae-a348-11e6-85e2-5a8594a96578.png)
Es erscheint zwar eine leere Seite, dennoch unschön.

**Comment by joachimdoerr** [comment]
sollte damit gefixt sein: https://github.com/FriendsOfREDAXO/mcalendar/commit/c24072ed64bdd84661c7b4af966d17567f184e90

**Comment by joachimdoerr** [comment]
done.
