### ISSUE TITLE
Fehler beim Anlegen eines neuen Events

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/mcalendar#9]
Nach Absenden des Formulars kommt der Fehler (»Fehler beim speichern!«), und die Felder Von/Bis sind leer, obwohl ich Zeiten eingetragen hatte.

REX 5.2
MCalendar mit Git-Stand von heute
Chrome 53 Mac

<img width="1440" alt="screenshot 2016-10-22 21 06 31" src="https://cloud.githubusercontent.com/assets/1297466/19621845/8b5e4244-989b-11e6-8074-e653c05ee1e9.png">

**Comment by joachimdoerr** [comment]
Gefixt: https://github.com/FriendsOfREDAXO/mcalendar/commit/1e8be904dee2335e0fa02b5dad391cea92bf95bf

**Comment by joachimdoerr** [comment]
ist wohl doch nicht gefixt. liegt anscheinend an der db Struktur - diese muss nochmals überarbeitet werden

**Comment by joachimdoerr** [comment]
ist nun tatsächlich gefixt: https://github.com/FriendsOfREDAXO/mcalendar/commit/6ca70949404b9d34d5176c047901680e8c7390fe
